import Head from "next/head";
import { Fragment } from "react";
import { Tabs, Tab, Card, CardBody } from "@nextui-org/react";
import { BiTrendingDown, BiTrendingUp } from "react-icons/bi";
import { MdDonutSmall, MdEventRepeat } from "react-icons/md";
import { FixedExpenses } from "./FixedExpenses";
import { FixedInflows } from "./FixedInflows";
import { Expenditures } from "./Expenditures";
import { Report } from "./Report";
import { type GetServerSideProps } from "next";
import { getServerAuthSession } from "~/server/auth";

export default function Transactions() {
  return (
    <Fragment>
      <Head>
        <title>My Finances | Transactions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <div className="flex w-full max-w-[1280px] flex-col gap-4 px-6 py-8">
          <Card>
            <CardBody>
              <Tabs aria-label="Options" color="secondary" variant="underlined">
                <Tab
                  key="report"
                  title={
                    <div className="flex items-center space-x-2">
                      <MdDonutSmall />
                      <span>Report</span>
                    </div>
                  }
                >
                  <Report />
                </Tab>

                <Tab
                  key="fixed-expenses"
                  title={
                    <div className="flex items-center space-x-2">
                      <MdEventRepeat />
                      <span>Fixed expenses</span>
                    </div>
                  }
                >
                  <FixedExpenses />
                </Tab>
                <Tab
                  key="expenditures"
                  title={
                    <div className="flex items-center space-x-2">
                      <BiTrendingDown />
                      <span>Expenditures</span>
                    </div>
                  }
                >
                  <Expenditures />
                </Tab>
                <Tab
                  key="fixed-inflows"
                  title={
                    <div className="flex items-center space-x-2">
                      <MdEventRepeat />
                      <span>Fixed inflows</span>
                    </div>
                  }
                >
                  <FixedInflows />
                </Tab>

                <Tab
                  key="inflows"
                  title={
                    <div className="flex items-center space-x-2">
                      <BiTrendingUp />
                      <span>Inflows</span>
                    </div>
                  }
                />
              </Tabs>
            </CardBody>
          </Card>
        </div>
      </main>
    </Fragment>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getServerAuthSession(ctx);

  if (!session?.user) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
};
